# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-12 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=13)),
            ],
        ),
    ]
